[project]
name = "simple-guardrails-example"
version = "0.1.0"
description = "Simple examples of implementing guardrails in LangGraph applications"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-openai>=0.3.28",
    "langgraph>=0.5.3",
    "python-dotenv>=1.0.0",
]
